# Generated by Django 4.1.7 on 2023-03-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_text', models.CharField(max_length=160)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ], 
        ),
    ]
